#!/bin/bash
sudo apt update
sudo apt upgrade
sudo apt dist-upgrade
sudo apt autoremove
sudo apt autoclean
sudo fwupdmgr get-devices
sudo fwupdmgr get-updates
sudo fwupdmgr update



#optimize
sudo sed -i "s|,discard||" /etc/fstab
cat /etc/fstab #should be no discard
sudo sed -i "s|,discard||" /etc/crypttab
cat /etc/crypttab #should be no discard
sudo systemctl enable fstrim.timer

sudo system76-power graphics hybrid

#install apps
sudo apt remove firefox geary -y
sudo apt install google-chrome-stable snapd caffein gparted gnome-tweak-tool nautilus-admin code ttf-mscorefonts-installer libavcodec-extra libdvd-pkg  -y
sudo dpkg-reconfigure libdvd-pkg






#install Wine
sudo dpkg --add-architecture i386
sudo apt update
sudo apt -y install software-properties-common wget
wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
sudo apt update
sudo apt install --install-recommends winehq-stable






# Themes
git clone https://github.com/vinceliuice/WhiteSur-gtk-theme.git
cd WhiteSur-gtk-theme
./install.sh




#REBOOT
sudo reboot now
